ldap:
    host: 192.168.15.5
    port: 389
    bind_user: "vagrant@uplift.local"
    bind_password: "vagrant"
    filterDN: "(&(objectClass=person)(memberOf:1.2.840.113556.1.4.1941:=CN=stuff,OU=uGroups,OU=DEMO01,DC=uplift,DC=local)(|(sAMAccountName={username})(mail={username})))"
	baseDN: "OU=DEMO01,DC=uplift,DC=local"
	loginUsername: "vagrant"
	loginPassword: "vagrant"